[package]
name = "volume_integration_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
crucible = { path = "../upstairs" }
hex = "0.4"
tokio = { version = "1.15.0", features = ["full"] }
rand = "0.8.4"
