[package]
name = "crucible-pantry-types"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
crucible-workspace-hack.workspace = true
schemars.workspace = true
serde.workspace = true
