[package]
name = "crucible-scope"
version = "0.0.0"
license = "MPL-2.0"
edition = "2018"
description = "crucible debugging tool for development work"

[dependencies]
anyhow = "1"
futures = "0.3"
futures-core = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.18.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"]}
toml = "0.5"
