[package]
name = "crucible-smf"
version = "0.0.0"
edition = "2021"

[dependencies]
libc.workspace = true
thiserror.workspace = true
num-traits.workspace = true
num-derive.workspace = true
crucible-workspace-hack.workspace = true
