[package]
name = "crucible-pantry-client"
version = "0.0.1"
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = [ "serde" ] }
percent-encoding = "2.2"
progenitor = { git = "https://github.com/oxidecomputer/progenitor", branch = "main" }
reqwest = { version = "0.11", default-features = false, features = ["json"] }
schemars = "0.8.12"
serde_json = "1.0"
uuid = { version = "1.3.0", features = [ "serde", "v4" ] }

[dependencies.serde]
version = "1.0"
features = [ "derive" ]
