[package]
name = "crucible-raw-extent"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
crucible-common.workspace = true
crucible-protocol.workspace = true
bincode.workspace = true

crucible-workspace-hack.workspace = true
